// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cmdhub_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCmdhubApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1917241248;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'cmdhub_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCmdhubApiCancelPipeline({required String runId});

  Future<Pipeline> crateApiCmdhubApiCreatePipeline({
    required Pipeline pipeline,
  });

  Future<Task> crateApiCmdhubApiCreateTask({required Task task});

  Future<void> crateApiCmdhubApiDeletePipeline({required String id});

  Future<void> crateApiCmdhubApiDeleteTask({required String id});

  Future<TaskInstance?> crateApiCmdhubApiGetInstance({
    required String instanceId,
  });

  Future<List<InstanceEvent>> crateApiCmdhubApiGetInstanceEventsSince({
    required int lastEventIndex,
  });

  Future<Pipeline?> crateApiCmdhubApiGetPipeline({required String id});

  Future<PipelineRunState?> crateApiCmdhubApiGetPipelineState({
    required String runId,
  });

  Future<Task?> crateApiCmdhubApiGetTask({required String id});

  Future<void> crateApiCmdhubApiInitApp();

  Future<void> crateApiCmdhubApiKillInstance({required String instanceId});

  Future<List<TaskInstance>> crateApiCmdhubApiListInstances();

  Future<List<PipelineRunState>> crateApiCmdhubApiListPipelineRuns();

  Future<List<Pipeline>> crateApiCmdhubApiListPipelines();

  Future<List<Task>> crateApiCmdhubApiListTasks();

  Future<Uint8List> crateApiCmdhubApiReadOutput({required String instanceId});

  Future<bool> crateApiCmdhubApiRemoveInstance({required String instanceId});

  Future<String> crateApiCmdhubApiRunPipeline({required String id});

  Future<int> crateApiCmdhubApiRunningCount();

  Future<TaskInstance> crateApiCmdhubApiSpawnTask({required String taskId});

  Future<Stream<InstanceEvent>> crateApiCmdhubApiSubscribeEvents();

  Future<Pipeline> crateApiCmdhubApiUpdatePipeline({
    required Pipeline pipeline,
  });

  Future<Task> crateApiCmdhubApiUpdateTask({required Task task});

  Future<void> crateApiCmdhubApiWriteInput({
    required String instanceId,
    required List<int> data,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCmdhubApiCancelPipeline({required String runId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(runId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiCancelPipelineConstMeta,
        argValues: [runId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiCancelPipelineConstMeta =>
      const TaskConstMeta(debugName: "cancel_pipeline", argNames: ["runId"]);

  @override
  Future<Pipeline> crateApiCmdhubApiCreatePipeline({
    required Pipeline pipeline,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_pipeline(pipeline, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pipeline,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiCreatePipelineConstMeta,
        argValues: [pipeline],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiCreatePipelineConstMeta =>
      const TaskConstMeta(debugName: "create_pipeline", argNames: ["pipeline"]);

  @override
  Future<Task> crateApiCmdhubApiCreateTask({required Task task}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_task(task, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiCreateTaskConstMeta,
        argValues: [task],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiCreateTaskConstMeta =>
      const TaskConstMeta(debugName: "create_task", argNames: ["task"]);

  @override
  Future<void> crateApiCmdhubApiDeletePipeline({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiDeletePipelineConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiDeletePipelineConstMeta =>
      const TaskConstMeta(debugName: "delete_pipeline", argNames: ["id"]);

  @override
  Future<void> crateApiCmdhubApiDeleteTask({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiDeleteTaskConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiDeleteTaskConstMeta =>
      const TaskConstMeta(debugName: "delete_task", argNames: ["id"]);

  @override
  Future<TaskInstance?> crateApiCmdhubApiGetInstance({
    required String instanceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(instanceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_task_instance,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiGetInstanceConstMeta,
        argValues: [instanceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiGetInstanceConstMeta =>
      const TaskConstMeta(debugName: "get_instance", argNames: ["instanceId"]);

  @override
  Future<List<InstanceEvent>> crateApiCmdhubApiGetInstanceEventsSince({
    required int lastEventIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(lastEventIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_instance_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiGetInstanceEventsSinceConstMeta,
        argValues: [lastEventIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiGetInstanceEventsSinceConstMeta =>
      const TaskConstMeta(
        debugName: "get_instance_events_since",
        argNames: ["lastEventIndex"],
      );

  @override
  Future<Pipeline?> crateApiCmdhubApiGetPipeline({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_pipeline,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiGetPipelineConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiGetPipelineConstMeta =>
      const TaskConstMeta(debugName: "get_pipeline", argNames: ["id"]);

  @override
  Future<PipelineRunState?> crateApiCmdhubApiGetPipelineState({
    required String runId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(runId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_pipeline_run_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiGetPipelineStateConstMeta,
        argValues: [runId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiGetPipelineStateConstMeta =>
      const TaskConstMeta(debugName: "get_pipeline_state", argNames: ["runId"]);

  @override
  Future<Task?> crateApiCmdhubApiGetTask({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_task,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiGetTaskConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiGetTaskConstMeta =>
      const TaskConstMeta(debugName: "get_task", argNames: ["id"]);

  @override
  Future<void> crateApiCmdhubApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCmdhubApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiCmdhubApiKillInstance({required String instanceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(instanceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiKillInstanceConstMeta,
        argValues: [instanceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiKillInstanceConstMeta =>
      const TaskConstMeta(debugName: "kill_instance", argNames: ["instanceId"]);

  @override
  Future<List<TaskInstance>> crateApiCmdhubApiListInstances() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_task_instance,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiListInstancesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiListInstancesConstMeta =>
      const TaskConstMeta(debugName: "list_instances", argNames: []);

  @override
  Future<List<PipelineRunState>> crateApiCmdhubApiListPipelineRuns() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pipeline_run_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiListPipelineRunsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiListPipelineRunsConstMeta =>
      const TaskConstMeta(debugName: "list_pipeline_runs", argNames: []);

  @override
  Future<List<Pipeline>> crateApiCmdhubApiListPipelines() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pipeline,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiListPipelinesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiListPipelinesConstMeta =>
      const TaskConstMeta(debugName: "list_pipelines", argNames: []);

  @override
  Future<List<Task>> crateApiCmdhubApiListTasks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_task,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiListTasksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiListTasksConstMeta =>
      const TaskConstMeta(debugName: "list_tasks", argNames: []);

  @override
  Future<Uint8List> crateApiCmdhubApiReadOutput({required String instanceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(instanceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiReadOutputConstMeta,
        argValues: [instanceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiReadOutputConstMeta =>
      const TaskConstMeta(debugName: "read_output", argNames: ["instanceId"]);

  @override
  Future<bool> crateApiCmdhubApiRemoveInstance({required String instanceId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(instanceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiRemoveInstanceConstMeta,
        argValues: [instanceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiRemoveInstanceConstMeta =>
      const TaskConstMeta(
        debugName: "remove_instance",
        argNames: ["instanceId"],
      );

  @override
  Future<String> crateApiCmdhubApiRunPipeline({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiRunPipelineConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiRunPipelineConstMeta =>
      const TaskConstMeta(debugName: "run_pipeline", argNames: ["id"]);

  @override
  Future<int> crateApiCmdhubApiRunningCount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiRunningCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiRunningCountConstMeta =>
      const TaskConstMeta(debugName: "running_count", argNames: []);

  @override
  Future<TaskInstance> crateApiCmdhubApiSpawnTask({required String taskId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_instance,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiSpawnTaskConstMeta,
        argValues: [taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiSpawnTaskConstMeta =>
      const TaskConstMeta(debugName: "spawn_task", argNames: ["taskId"]);

  @override
  Future<Stream<InstanceEvent>> crateApiCmdhubApiSubscribeEvents() async {
    final sink = RustStreamSink<InstanceEvent>();
    await handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_instance_event_Sse(sink, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCmdhubApiSubscribeEventsConstMeta,
        argValues: [sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCmdhubApiSubscribeEventsConstMeta =>
      const TaskConstMeta(debugName: "subscribe_events", argNames: ["sink"]);

  @override
  Future<Pipeline> crateApiCmdhubApiUpdatePipeline({
    required Pipeline pipeline,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_pipeline(pipeline, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pipeline,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiUpdatePipelineConstMeta,
        argValues: [pipeline],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiUpdatePipelineConstMeta =>
      const TaskConstMeta(debugName: "update_pipeline", argNames: ["pipeline"]);

  @override
  Future<Task> crateApiCmdhubApiUpdateTask({required Task task}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_task(task, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiUpdateTaskConstMeta,
        argValues: [task],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiUpdateTaskConstMeta =>
      const TaskConstMeta(debugName: "update_task", argNames: ["task"]);

  @override
  Future<void> crateApiCmdhubApiWriteInput({
    required String instanceId,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(instanceId, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCmdhubApiWriteInputConstMeta,
        argValues: [instanceId, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCmdhubApiWriteInputConstMeta =>
      const TaskConstMeta(
        debugName: "write_input",
        argNames: ["instanceId", "data"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  RustStreamSink<InstanceEvent> dco_decode_StreamSink_instance_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Pipeline dco_decode_box_autoadd_pipeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pipeline(raw);
  }

  @protected
  PipelineRunState dco_decode_box_autoadd_pipeline_run_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pipeline_run_state(raw);
  }

  @protected
  Task dco_decode_box_autoadd_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_task(raw);
  }

  @protected
  TaskInstance dco_decode_box_autoadd_task_instance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_task_instance(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  InstanceEvent dco_decode_instance_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return InstanceEvent_Started(
          dco_decode_box_autoadd_task_instance(raw[1]),
        );
      case 1:
        return InstanceEvent_Output(
          instanceId: dco_decode_String(raw[1]),
          text: dco_decode_String(raw[2]),
        );
      case 2:
        return InstanceEvent_Exited(
          dco_decode_box_autoadd_task_instance(raw[1]),
        );
      case 3:
        return InstanceEvent_Error(
          instanceId: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  InstanceStatus dco_decode_instance_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return InstanceStatus_Running();
      case 1:
        return InstanceStatus_Exited(code: dco_decode_u_32(raw[1]));
      case 2:
        return InstanceStatus_Killed();
      case 3:
        return InstanceStatus_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<InstanceEvent> dco_decode_list_instance_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_instance_event).toList();
  }

  @protected
  List<Pipeline> dco_decode_list_pipeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pipeline).toList();
  }

  @protected
  List<PipelineRunState> dco_decode_list_pipeline_run_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pipeline_run_state).toList();
  }

  @protected
  List<PipelineStep> dco_decode_list_pipeline_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pipeline_step).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<StepState> dco_decode_list_step_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_step_state).toList();
  }

  @protected
  List<Task> dco_decode_list_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_task).toList();
  }

  @protected
  List<TaskInstance> dco_decode_list_task_instance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_task_instance).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Pipeline? dco_decode_opt_box_autoadd_pipeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_pipeline(raw);
  }

  @protected
  PipelineRunState? dco_decode_opt_box_autoadd_pipeline_run_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_pipeline_run_state(raw);
  }

  @protected
  Task? dco_decode_opt_box_autoadd_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_task(raw);
  }

  @protected
  TaskInstance? dco_decode_opt_box_autoadd_task_instance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_task_instance(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Pipeline dco_decode_pipeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Pipeline(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      steps: dco_decode_list_pipeline_step(arr[2]),
    );
  }

  @protected
  PipelineRunState dco_decode_pipeline_run_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PipelineRunState(
      runId: dco_decode_String(arr[0]),
      pipelineId: dco_decode_String(arr[1]),
      pipelineName: dco_decode_String(arr[2]),
      stepStates: dco_decode_list_step_state(arr[3]),
      status: dco_decode_pipeline_status(arr[4]),
      startedAt: dco_decode_u_64(arr[5]),
      endedAt: dco_decode_opt_box_autoadd_u_64(arr[6]),
    );
  }

  @protected
  PipelineStatus dco_decode_pipeline_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PipelineStatus.values[raw as int];
  }

  @protected
  PipelineStep dco_decode_pipeline_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PipelineStep(
      taskId: dco_decode_String(arr[0]),
      order: dco_decode_u_32(arr[1]),
      delayMs: dco_decode_u_64(arr[2]),
      condition: dco_decode_step_condition(arr[3]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  StepCondition dco_decode_step_condition(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StepCondition.values[raw as int];
  }

  @protected
  StepState dco_decode_step_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return StepState_Pending();
      case 1:
        return StepState_Running(instanceId: dco_decode_String(raw[1]));
      case 2:
        return StepState_Completed(
          instanceId: dco_decode_String(raw[1]),
          exitCode: dco_decode_u_32(raw[2]),
        );
      case 3:
        return StepState_Failed(error: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  Task dco_decode_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Task(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      command: dco_decode_String(arr[2]),
      cwd: dco_decode_opt_String(arr[3]),
      env: dco_decode_Map_String_String_None(arr[4]),
      envInherit: dco_decode_bool(arr[5]),
      mode: dco_decode_task_mode(arr[6]),
    );
  }

  @protected
  TaskInstance dco_decode_task_instance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return TaskInstance(
      id: dco_decode_String(arr[0]),
      taskId: dco_decode_String(arr[1]),
      taskName: dco_decode_String(arr[2]),
      command: dco_decode_String(arr[3]),
      status: dco_decode_instance_status(arr[4]),
      startedAt: dco_decode_u_64(arr[5]),
      endedAt: dco_decode_opt_box_autoadd_u_64(arr[6]),
      childPid: dco_decode_opt_box_autoadd_u_32(arr[7]),
      runId: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  TaskMode dco_decode_task_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TaskMode.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  RustStreamSink<InstanceEvent> sse_decode_StreamSink_instance_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Pipeline sse_decode_box_autoadd_pipeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pipeline(deserializer));
  }

  @protected
  PipelineRunState sse_decode_box_autoadd_pipeline_run_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pipeline_run_state(deserializer));
  }

  @protected
  Task sse_decode_box_autoadd_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_task(deserializer));
  }

  @protected
  TaskInstance sse_decode_box_autoadd_task_instance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_task_instance(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  InstanceEvent sse_decode_instance_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_task_instance(deserializer);
        return InstanceEvent_Started(var_field0);
      case 1:
        var var_instanceId = sse_decode_String(deserializer);
        var var_text = sse_decode_String(deserializer);
        return InstanceEvent_Output(instanceId: var_instanceId, text: var_text);
      case 2:
        var var_field0 = sse_decode_box_autoadd_task_instance(deserializer);
        return InstanceEvent_Exited(var_field0);
      case 3:
        var var_instanceId = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return InstanceEvent_Error(
          instanceId: var_instanceId,
          message: var_message,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  InstanceStatus sse_decode_instance_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return InstanceStatus_Running();
      case 1:
        var var_code = sse_decode_u_32(deserializer);
        return InstanceStatus_Exited(code: var_code);
      case 2:
        return InstanceStatus_Killed();
      case 3:
        var var_message = sse_decode_String(deserializer);
        return InstanceStatus_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<InstanceEvent> sse_decode_list_instance_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InstanceEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_instance_event(deserializer));
    }
    return ans_;
  }

  @protected
  List<Pipeline> sse_decode_list_pipeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Pipeline>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pipeline(deserializer));
    }
    return ans_;
  }

  @protected
  List<PipelineRunState> sse_decode_list_pipeline_run_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PipelineRunState>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pipeline_run_state(deserializer));
    }
    return ans_;
  }

  @protected
  List<PipelineStep> sse_decode_list_pipeline_step(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PipelineStep>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pipeline_step(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<StepState> sse_decode_list_step_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StepState>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_step_state(deserializer));
    }
    return ans_;
  }

  @protected
  List<Task> sse_decode_list_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Task>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_task(deserializer));
    }
    return ans_;
  }

  @protected
  List<TaskInstance> sse_decode_list_task_instance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TaskInstance>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_task_instance(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Pipeline? sse_decode_opt_box_autoadd_pipeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pipeline(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PipelineRunState? sse_decode_opt_box_autoadd_pipeline_run_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pipeline_run_state(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Task? sse_decode_opt_box_autoadd_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_task(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TaskInstance? sse_decode_opt_box_autoadd_task_instance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_task_instance(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Pipeline sse_decode_pipeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_steps = sse_decode_list_pipeline_step(deserializer);
    return Pipeline(id: var_id, name: var_name, steps: var_steps);
  }

  @protected
  PipelineRunState sse_decode_pipeline_run_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_runId = sse_decode_String(deserializer);
    var var_pipelineId = sse_decode_String(deserializer);
    var var_pipelineName = sse_decode_String(deserializer);
    var var_stepStates = sse_decode_list_step_state(deserializer);
    var var_status = sse_decode_pipeline_status(deserializer);
    var var_startedAt = sse_decode_u_64(deserializer);
    var var_endedAt = sse_decode_opt_box_autoadd_u_64(deserializer);
    return PipelineRunState(
      runId: var_runId,
      pipelineId: var_pipelineId,
      pipelineName: var_pipelineName,
      stepStates: var_stepStates,
      status: var_status,
      startedAt: var_startedAt,
      endedAt: var_endedAt,
    );
  }

  @protected
  PipelineStatus sse_decode_pipeline_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PipelineStatus.values[inner];
  }

  @protected
  PipelineStep sse_decode_pipeline_step(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_taskId = sse_decode_String(deserializer);
    var var_order = sse_decode_u_32(deserializer);
    var var_delayMs = sse_decode_u_64(deserializer);
    var var_condition = sse_decode_step_condition(deserializer);
    return PipelineStep(
      taskId: var_taskId,
      order: var_order,
      delayMs: var_delayMs,
      condition: var_condition,
    );
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  StepCondition sse_decode_step_condition(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return StepCondition.values[inner];
  }

  @protected
  StepState sse_decode_step_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return StepState_Pending();
      case 1:
        var var_instanceId = sse_decode_String(deserializer);
        return StepState_Running(instanceId: var_instanceId);
      case 2:
        var var_instanceId = sse_decode_String(deserializer);
        var var_exitCode = sse_decode_u_32(deserializer);
        return StepState_Completed(
          instanceId: var_instanceId,
          exitCode: var_exitCode,
        );
      case 3:
        var var_error = sse_decode_String(deserializer);
        return StepState_Failed(error: var_error);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  Task sse_decode_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_command = sse_decode_String(deserializer);
    var var_cwd = sse_decode_opt_String(deserializer);
    var var_env = sse_decode_Map_String_String_None(deserializer);
    var var_envInherit = sse_decode_bool(deserializer);
    var var_mode = sse_decode_task_mode(deserializer);
    return Task(
      id: var_id,
      name: var_name,
      command: var_command,
      cwd: var_cwd,
      env: var_env,
      envInherit: var_envInherit,
      mode: var_mode,
    );
  }

  @protected
  TaskInstance sse_decode_task_instance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_taskId = sse_decode_String(deserializer);
    var var_taskName = sse_decode_String(deserializer);
    var var_command = sse_decode_String(deserializer);
    var var_status = sse_decode_instance_status(deserializer);
    var var_startedAt = sse_decode_u_64(deserializer);
    var var_endedAt = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_childPid = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_runId = sse_decode_opt_String(deserializer);
    return TaskInstance(
      id: var_id,
      taskId: var_taskId,
      taskName: var_taskName,
      command: var_command,
      status: var_status,
      startedAt: var_startedAt,
      endedAt: var_endedAt,
      childPid: var_childPid,
      runId: var_runId,
    );
  }

  @protected
  TaskMode sse_decode_task_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TaskMode.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_instance_event_Sse(
    RustStreamSink<InstanceEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_instance_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_pipeline(
    Pipeline self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pipeline(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pipeline_run_state(
    PipelineRunState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pipeline_run_state(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_task(Task self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_task(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_task_instance(
    TaskInstance self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_task_instance(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_instance_event(InstanceEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case InstanceEvent_Started(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_task_instance(field0, serializer);
      case InstanceEvent_Output(instanceId: final instanceId, text: final text):
        sse_encode_i_32(1, serializer);
        sse_encode_String(instanceId, serializer);
        sse_encode_String(text, serializer);
      case InstanceEvent_Exited(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_task_instance(field0, serializer);
      case InstanceEvent_Error(
        instanceId: final instanceId,
        message: final message,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(instanceId, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_instance_status(
    InstanceStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case InstanceStatus_Running():
        sse_encode_i_32(0, serializer);
      case InstanceStatus_Exited(code: final code):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(code, serializer);
      case InstanceStatus_Killed():
        sse_encode_i_32(2, serializer);
      case InstanceStatus_Error(message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_list_instance_event(
    List<InstanceEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_instance_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pipeline(List<Pipeline> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pipeline(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pipeline_run_state(
    List<PipelineRunState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pipeline_run_state(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pipeline_step(
    List<PipelineStep> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pipeline_step(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_step_state(
    List<StepState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_step_state(item, serializer);
    }
  }

  @protected
  void sse_encode_list_task(List<Task> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_task(item, serializer);
    }
  }

  @protected
  void sse_encode_list_task_instance(
    List<TaskInstance> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_task_instance(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pipeline(
    Pipeline? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pipeline(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pipeline_run_state(
    PipelineRunState? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pipeline_run_state(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_task(Task? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_task(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_task_instance(
    TaskInstance? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_task_instance(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_pipeline(Pipeline self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_pipeline_step(self.steps, serializer);
  }

  @protected
  void sse_encode_pipeline_run_state(
    PipelineRunState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.runId, serializer);
    sse_encode_String(self.pipelineId, serializer);
    sse_encode_String(self.pipelineName, serializer);
    sse_encode_list_step_state(self.stepStates, serializer);
    sse_encode_pipeline_status(self.status, serializer);
    sse_encode_u_64(self.startedAt, serializer);
    sse_encode_opt_box_autoadd_u_64(self.endedAt, serializer);
  }

  @protected
  void sse_encode_pipeline_status(
    PipelineStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_pipeline_step(PipelineStep self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.taskId, serializer);
    sse_encode_u_32(self.order, serializer);
    sse_encode_u_64(self.delayMs, serializer);
    sse_encode_step_condition(self.condition, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_step_condition(StepCondition self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_step_state(StepState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StepState_Pending():
        sse_encode_i_32(0, serializer);
      case StepState_Running(instanceId: final instanceId):
        sse_encode_i_32(1, serializer);
        sse_encode_String(instanceId, serializer);
      case StepState_Completed(
        instanceId: final instanceId,
        exitCode: final exitCode,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(instanceId, serializer);
        sse_encode_u_32(exitCode, serializer);
      case StepState_Failed(error: final error):
        sse_encode_i_32(3, serializer);
        sse_encode_String(error, serializer);
    }
  }

  @protected
  void sse_encode_task(Task self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.command, serializer);
    sse_encode_opt_String(self.cwd, serializer);
    sse_encode_Map_String_String_None(self.env, serializer);
    sse_encode_bool(self.envInherit, serializer);
    sse_encode_task_mode(self.mode, serializer);
  }

  @protected
  void sse_encode_task_instance(TaskInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.taskId, serializer);
    sse_encode_String(self.taskName, serializer);
    sse_encode_String(self.command, serializer);
    sse_encode_instance_status(self.status, serializer);
    sse_encode_u_64(self.startedAt, serializer);
    sse_encode_opt_box_autoadd_u_64(self.endedAt, serializer);
    sse_encode_opt_box_autoadd_u_32(self.childPid, serializer);
    sse_encode_opt_String(self.runId, serializer);
  }

  @protected
  void sse_encode_task_mode(TaskMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
