// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cmdhub_api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Pipeline dco_decode_box_autoadd_pipeline(dynamic raw);

  @protected
  PipelineRunState dco_decode_box_autoadd_pipeline_run_state(dynamic raw);

  @protected
  Task dco_decode_box_autoadd_task(dynamic raw);

  @protected
  TaskInstance dco_decode_box_autoadd_task_instance(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InstanceEvent dco_decode_instance_event(dynamic raw);

  @protected
  InstanceStatus dco_decode_instance_status(dynamic raw);

  @protected
  List<InstanceEvent> dco_decode_list_instance_event(dynamic raw);

  @protected
  List<Pipeline> dco_decode_list_pipeline(dynamic raw);

  @protected
  List<PipelineRunState> dco_decode_list_pipeline_run_state(dynamic raw);

  @protected
  List<PipelineStep> dco_decode_list_pipeline_step(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<StepState> dco_decode_list_step_state(dynamic raw);

  @protected
  List<Task> dco_decode_list_task(dynamic raw);

  @protected
  List<TaskInstance> dco_decode_list_task_instance(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Pipeline? dco_decode_opt_box_autoadd_pipeline(dynamic raw);

  @protected
  PipelineRunState? dco_decode_opt_box_autoadd_pipeline_run_state(dynamic raw);

  @protected
  Task? dco_decode_opt_box_autoadd_task(dynamic raw);

  @protected
  TaskInstance? dco_decode_opt_box_autoadd_task_instance(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Pipeline dco_decode_pipeline(dynamic raw);

  @protected
  PipelineRunState dco_decode_pipeline_run_state(dynamic raw);

  @protected
  PipelineStatus dco_decode_pipeline_status(dynamic raw);

  @protected
  PipelineStep dco_decode_pipeline_step(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  StepCondition dco_decode_step_condition(dynamic raw);

  @protected
  StepState dco_decode_step_state(dynamic raw);

  @protected
  Task dco_decode_task(dynamic raw);

  @protected
  TaskInstance dco_decode_task_instance(dynamic raw);

  @protected
  TaskMode dco_decode_task_mode(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Pipeline sse_decode_box_autoadd_pipeline(SseDeserializer deserializer);

  @protected
  PipelineRunState sse_decode_box_autoadd_pipeline_run_state(
    SseDeserializer deserializer,
  );

  @protected
  Task sse_decode_box_autoadd_task(SseDeserializer deserializer);

  @protected
  TaskInstance sse_decode_box_autoadd_task_instance(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InstanceEvent sse_decode_instance_event(SseDeserializer deserializer);

  @protected
  InstanceStatus sse_decode_instance_status(SseDeserializer deserializer);

  @protected
  List<InstanceEvent> sse_decode_list_instance_event(
    SseDeserializer deserializer,
  );

  @protected
  List<Pipeline> sse_decode_list_pipeline(SseDeserializer deserializer);

  @protected
  List<PipelineRunState> sse_decode_list_pipeline_run_state(
    SseDeserializer deserializer,
  );

  @protected
  List<PipelineStep> sse_decode_list_pipeline_step(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<StepState> sse_decode_list_step_state(SseDeserializer deserializer);

  @protected
  List<Task> sse_decode_list_task(SseDeserializer deserializer);

  @protected
  List<TaskInstance> sse_decode_list_task_instance(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Pipeline? sse_decode_opt_box_autoadd_pipeline(SseDeserializer deserializer);

  @protected
  PipelineRunState? sse_decode_opt_box_autoadd_pipeline_run_state(
    SseDeserializer deserializer,
  );

  @protected
  Task? sse_decode_opt_box_autoadd_task(SseDeserializer deserializer);

  @protected
  TaskInstance? sse_decode_opt_box_autoadd_task_instance(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Pipeline sse_decode_pipeline(SseDeserializer deserializer);

  @protected
  PipelineRunState sse_decode_pipeline_run_state(SseDeserializer deserializer);

  @protected
  PipelineStatus sse_decode_pipeline_status(SseDeserializer deserializer);

  @protected
  PipelineStep sse_decode_pipeline_step(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  StepCondition sse_decode_step_condition(SseDeserializer deserializer);

  @protected
  StepState sse_decode_step_state(SseDeserializer deserializer);

  @protected
  Task sse_decode_task(SseDeserializer deserializer);

  @protected
  TaskInstance sse_decode_task_instance(SseDeserializer deserializer);

  @protected
  TaskMode sse_decode_task_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pipeline(Pipeline self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pipeline_run_state(
    PipelineRunState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_task(Task self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_task_instance(
    TaskInstance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_instance_event(InstanceEvent self, SseSerializer serializer);

  @protected
  void sse_encode_instance_status(
    InstanceStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_instance_event(
    List<InstanceEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pipeline(List<Pipeline> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pipeline_run_state(
    List<PipelineRunState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pipeline_step(
    List<PipelineStep> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_step_state(
    List<StepState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_task(List<Task> self, SseSerializer serializer);

  @protected
  void sse_encode_list_task_instance(
    List<TaskInstance> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_pipeline(
    Pipeline? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pipeline_run_state(
    PipelineRunState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_task(Task? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_task_instance(
    TaskInstance? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_pipeline(Pipeline self, SseSerializer serializer);

  @protected
  void sse_encode_pipeline_run_state(
    PipelineRunState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pipeline_status(
    PipelineStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pipeline_step(PipelineStep self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_step_condition(StepCondition self, SseSerializer serializer);

  @protected
  void sse_encode_step_state(StepState self, SseSerializer serializer);

  @protected
  void sse_encode_task(Task self, SseSerializer serializer);

  @protected
  void sse_encode_task_instance(TaskInstance self, SseSerializer serializer);

  @protected
  void sse_encode_task_mode(TaskMode self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
