// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

@freezed
sealed class InstanceEvent with _$InstanceEvent {
  const InstanceEvent._();

  const factory InstanceEvent.started(TaskInstance field0) =
      InstanceEvent_Started;
  const factory InstanceEvent.output({
    required String instanceId,

    /// UTF-8 解码后的文本增量
    required String text,
  }) = InstanceEvent_Output;
  const factory InstanceEvent.exited(TaskInstance field0) =
      InstanceEvent_Exited;
  const factory InstanceEvent.error({
    required String instanceId,
    required String message,
  }) = InstanceEvent_Error;
}

@freezed
sealed class InstanceStatus with _$InstanceStatus {
  const InstanceStatus._();

  const factory InstanceStatus.running() = InstanceStatus_Running;
  const factory InstanceStatus.exited({required int code}) =
      InstanceStatus_Exited;
  const factory InstanceStatus.error({required String message}) =
      InstanceStatus_Error;
}

class InstanceStatus_Killed extends InstanceStatus {
  const InstanceStatus_Killed() : super._();

  @override
  String toString() => 'InstanceStatus.killed()';

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is InstanceStatus_Killed;

  @override
  int get hashCode => runtimeType.hashCode;
}

/// 编排：一组按顺序执行的任务
class Pipeline {
  final String id;
  final String name;
  final List<PipelineStep> steps;

  const Pipeline({required this.id, required this.name, required this.steps});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ steps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Pipeline &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          steps == other.steps;
}

/// 编排运行状态
class PipelineRunState {
  final String runId;
  final String pipelineId;
  final String pipelineName;
  final List<StepState> stepStates;
  final PipelineStatus status;
  final BigInt startedAt;
  final BigInt? endedAt;

  const PipelineRunState({
    required this.runId,
    required this.pipelineId,
    required this.pipelineName,
    required this.stepStates,
    required this.status,
    required this.startedAt,
    this.endedAt,
  });

  @override
  int get hashCode =>
      runId.hashCode ^
      pipelineId.hashCode ^
      pipelineName.hashCode ^
      stepStates.hashCode ^
      status.hashCode ^
      startedAt.hashCode ^
      endedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PipelineRunState &&
          runtimeType == other.runtimeType &&
          runId == other.runId &&
          pipelineId == other.pipelineId &&
          pipelineName == other.pipelineName &&
          stepStates == other.stepStates &&
          status == other.status &&
          startedAt == other.startedAt &&
          endedAt == other.endedAt;
}

/// 编排运行状态
enum PipelineStatus { running, completed, failed, cancelled }

/// 编排步骤
class PipelineStep {
  /// 引用的 Task id
  final String taskId;

  /// 执行序号
  final int order;

  /// 本步启动前的额外延时（毫秒）
  final BigInt delayMs;

  /// 触发条件
  final StepCondition condition;

  const PipelineStep({
    required this.taskId,
    required this.order,
    required this.delayMs,
    required this.condition,
  });

  @override
  int get hashCode =>
      taskId.hashCode ^ order.hashCode ^ delayMs.hashCode ^ condition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PipelineStep &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          order == other.order &&
          delayMs == other.delayMs &&
          condition == other.condition;
}

/// 编排步骤的触发条件
enum StepCondition {
  /// 编排启动时立即执行（仅第一步有效）
  onStart,

  /// 上一步进程退出后执行
  afterPrevious,

  /// 上一步启动后再等指定毫秒后执行（不等退出）
  afterDelay,
}

@freezed
sealed class StepState with _$StepState {
  const StepState._();

  const factory StepState.pending() = StepState_Pending;
  const factory StepState.running({required String instanceId}) =
      StepState_Running;
  const factory StepState.completed({
    required String instanceId,
    required int exitCode,
  }) = StepState_Completed;
  const factory StepState.failed({required String error}) = StepState_Failed;
}

/// 任务定义：对应命令行的单条命令
class Task {
  /// 唯一标识，UUID v4
  final String id;

  /// 前端显示名
  final String name;

  /// 实际执行的命令
  final String command;

  /// 工作路径
  final String? cwd;

  /// 额外环境变量（追加到系统环境）
  final Map<String, String> env;

  /// 是否继承系统环境变量，默认 true
  final bool envInherit;

  /// 执行模式
  final TaskMode mode;

  const Task({
    required this.id,
    required this.name,
    required this.command,
    this.cwd,
    required this.env,
    required this.envInherit,
    required this.mode,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      command.hashCode ^
      cwd.hashCode ^
      env.hashCode ^
      envInherit.hashCode ^
      mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Task &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          command == other.command &&
          cwd == other.cwd &&
          env == other.env &&
          envInherit == other.envInherit &&
          mode == other.mode;
}

/// 任务实例：一次任务执行
class TaskInstance {
  /// instance-{task_id}-{counter}
  final String id;
  final String taskId;
  final String taskName;
  final String command;
  final InstanceStatus status;

  /// Unix 时间戳
  final BigInt startedAt;
  final BigInt? endedAt;
  final int? childPid;
  final String? runId;

  const TaskInstance({
    required this.id,
    required this.taskId,
    required this.taskName,
    required this.command,
    required this.status,
    required this.startedAt,
    this.endedAt,
    this.childPid,
    this.runId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      taskId.hashCode ^
      taskName.hashCode ^
      command.hashCode ^
      status.hashCode ^
      startedAt.hashCode ^
      endedAt.hashCode ^
      childPid.hashCode ^
      runId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskInstance &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          taskId == other.taskId &&
          taskName == other.taskName &&
          command == other.command &&
          status == other.status &&
          startedAt == other.startedAt &&
          endedAt == other.endedAt &&
          childPid == other.childPid &&
          runId == other.runId;
}

/// 执行模式
enum TaskMode {
  /// shell -c 一次性执行，命令退出即结束
  oneshot,

  /// 交互式 shell，保持 PTY 供后续输入
  interactive,
}
