// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `executor`, `pipeline_runner`, `tokio_runtime`

Future<Task> createTask({required Task task}) =>
    RustLib.instance.api.crateApiCmdhubApiCreateTask(task: task);

Future<Task> updateTask({required Task task}) =>
    RustLib.instance.api.crateApiCmdhubApiUpdateTask(task: task);

Future<void> deleteTask({required String id}) =>
    RustLib.instance.api.crateApiCmdhubApiDeleteTask(id: id);

Future<List<Task>> listTasks() =>
    RustLib.instance.api.crateApiCmdhubApiListTasks();

Future<Task?> getTask({required String id}) =>
    RustLib.instance.api.crateApiCmdhubApiGetTask(id: id);

Future<Pipeline> createPipeline({required Pipeline pipeline}) =>
    RustLib.instance.api.crateApiCmdhubApiCreatePipeline(pipeline: pipeline);

Future<Pipeline> updatePipeline({required Pipeline pipeline}) =>
    RustLib.instance.api.crateApiCmdhubApiUpdatePipeline(pipeline: pipeline);

Future<void> deletePipeline({required String id}) =>
    RustLib.instance.api.crateApiCmdhubApiDeletePipeline(id: id);

Future<List<Pipeline>> listPipelines() =>
    RustLib.instance.api.crateApiCmdhubApiListPipelines();

Future<Pipeline?> getPipeline({required String id}) =>
    RustLib.instance.api.crateApiCmdhubApiGetPipeline(id: id);

Future<String> runPipeline({required String id}) =>
    RustLib.instance.api.crateApiCmdhubApiRunPipeline(id: id);

Future<void> cancelPipeline({required String runId}) =>
    RustLib.instance.api.crateApiCmdhubApiCancelPipeline(runId: runId);

Future<PipelineRunState?> getPipelineState({required String runId}) =>
    RustLib.instance.api.crateApiCmdhubApiGetPipelineState(runId: runId);

Future<List<PipelineRunState>> listPipelineRuns() =>
    RustLib.instance.api.crateApiCmdhubApiListPipelineRuns();

Future<TaskInstance> spawnTask({required String taskId}) =>
    RustLib.instance.api.crateApiCmdhubApiSpawnTask(taskId: taskId);

Future<void> killInstance({required String instanceId}) =>
    RustLib.instance.api.crateApiCmdhubApiKillInstance(instanceId: instanceId);

Future<List<TaskInstance>> listInstances() =>
    RustLib.instance.api.crateApiCmdhubApiListInstances();

Future<TaskInstance?> getInstance({required String instanceId}) =>
    RustLib.instance.api.crateApiCmdhubApiGetInstance(instanceId: instanceId);

Future<Uint8List> readOutput({required String instanceId}) =>
    RustLib.instance.api.crateApiCmdhubApiReadOutput(instanceId: instanceId);

Future<void> writeInput({
  required String instanceId,
  required List<int> data,
}) => RustLib.instance.api.crateApiCmdhubApiWriteInput(
  instanceId: instanceId,
  data: data,
);

Future<bool> removeInstance({required String instanceId}) => RustLib
    .instance
    .api
    .crateApiCmdhubApiRemoveInstance(instanceId: instanceId);

Future<int> runningCount() =>
    RustLib.instance.api.crateApiCmdhubApiRunningCount();

/// 获取指定索引之后的所有实例事件（增量拉取）
///
/// Flutter 端维护一个 last_index，每次调用传入上次的索引，
/// 只返回新事件，减少不必要的数据传输。
Future<List<InstanceEvent>> getInstanceEventsSince({
  required int lastEventIndex,
}) => RustLib.instance.api.crateApiCmdhubApiGetInstanceEventsSince(
  lastEventIndex: lastEventIndex,
);
